### ISSUE TITLE
Allow to add a filter to build pull-requests only, and filter for tags

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/bitrise.io#40]
Related UserVoice links:

* https://bitrise.uservoice.com/forums/235233-general/suggestions/10805625-allow-to-add-a-filter-to-build-pull-requests-only
* https://bitrise.uservoice.com/forums/235233-general/suggestions/10476936-ability-to-trigger-a-step-or-workflow-only-if-ther

Extend `trigger_map` (http://devcenter.bitrise.io/docs/lesson-6-pull-the-trigger-on-the-workflow) to be able to:

* specify a `pattern` which should only match in case of Pull Request
* in case of Pull Request add an option to specify against which branch the pattern should be matched: the source or the target of the PR
* allow a `pattern` to be matched against `tags`

## Proposal

```
trigger_map:
  - pattern: master
    is_pull_request_allowed: true # default is false
    is_code_push_allowed: false # default is true
    match_against: target-branch # possible values: branch/source-branch/target-branch/tag
    workflow: feature
```

*advantage: the two option (`is_pull_request_allowed` & `is_code_push_allowed) could be presented as toggles on the (web) UI, no need to write it as text*

or

```
trigger_map:
  - pattern: master
    events: [code-push, pull-request] # default value: [code-push] or [code-push, pull-request]
    match_against: target-branch # possible values: branch/source-branch/target-branch/tag
    workflow: feature
```

*compatibility note for this second form: `is_pull_request_allowed` would still be supported and used, unless you specify `events`, in which case `is_pull_request_allowed` would be ignored*

*This (`events`) would be presented as two check-boxes on the (Web) UI.*

**Let us know what you think about this proposal!**

**Comment by timotei** [comment]
I think maybe something like "runIf" toggle (if not very complex) per pattern would give 100% flexibility, because it allows us to construct some more complex conditions which take into account different scenarios.

For example, I had to execute a specific workflow (or skip it) if the changes were done on a given path (e.g., I don't want to build the app when I commit to the server-side code, which is in a specific path, compared to the mobile app).

If I'd had to chose **only** between the two, I'd pick the latest as it's more flexible (future-proof), and clear enough.

**Comment by viktorbenei** [comment]
@timotei Thanks for the feedback! We thought about a more powerful `run_if` like property too, but that would require more knowledge about how things work or to check the docs when you'd want to use it, as it would be a text based value, with a non obvious syntax. Advanced, but not easy. The problem with this is that most users start to tweak the triggers at an early stage, where they're still learning about how things work.

Another thing we have to consider is that checking the `trigger_map` happens on a separate machine, not on the build server. This is required to make it possible to not to start builds if your `trigger_map` is configured that way (e.g. you only build your `master` branch). Creating & destroying a full VM (especially macOS ones) take too much time to just check the `trigger_map` and declare that this shouldn't even start a build. This means that you can't check files for example, as the files are not there at that point, only the `bitrise.yml` is.

We're still thinking about a `run_if` like option, which could check at least Env Vars or mode flags (eg `.IsCI`), but so far it seems that it wouldn't allow more advanced use cases than the ones in our current proposal (because of the lack of access to files etc.) and it'd just complicate the usage (instead of checkboxes / toggles you should provide the expression as text).

We think that our proposal would be a good solution for the use cases reported for this feature request so far, but if you or anyone else have a use case which would not be possible even with this new syntax please let us know!

This is still a proposal and can be changed! We'll start to work on it in about a month, so if anyone reports a use case not covered by this proposal there's still time to discuss it & to change the proposal!

**Comment by viktorbenei** [comment]
Another note: even if we implement the feature as it is proposed here it can be extended in the future. The only thing what have to be considered is that we don't want to break backward compatibility, as much as possible. Adding a new, more advanced option is acceptable as long as sensible compatibility can be defined, like `events` in our proposal (-> *compatibility note for this second form: `is_pull_request_allowed` would still be supported and used, unless you specify `events`, in which case `is_pull_request_allowed` would be ignored*)

**Comment by tlvenn** [comment]
any update on when this might be implemented ?

**Comment by viktorbenei** [comment]
@tlvenn no hard ETA yet, but we hope to ship it in 1-2 months

**Comment by tlvenn** [comment]
wow that's a pretty long time. Is there any chance we could have an simpler interim solution ? Like a simple `is_pull_request_required` ?

**Comment by viktorbenei** [comment]
The problem is, this requires changes in multiple components, including the Bitrise CLI which we publish a release for monthly, and these changes won't fit into this month's release (scheduled for next Thursday), but we'll do everything to include the changes in next month's CLI release (second Thursday of the month).

**Comment by jayvdb** [comment]
A more flexible approach would help open source projects that are limited to 200 builds.  That sounds like a lot, but it can quickly be used up if someone is doing lots of small commits, especially if they are doing documentation (the Github edit functionality is ... too easy ...).

It would be very helpful to be able to exclude builds when the modified files all match defined path/glob/etc.

**Comment by viktorbenei** [comment]
@jayvdb great idea and thanks for the feedback! The issue with checking files is that we support lots of different types of git hosting services, even self hosted ones, where you don't have a webhook which would include every file change. This means that we should still git clone the repo somewhere and check for file changes to be able to determine whether the build should start. Not impossible, but out of scope for this feature request. That said, if you want to, feel free to create a new feature request! ;)

**Comment by jayvdb** [comment]
Done (48, and less related 47).  A simpler approach, more in line with what has been discussed above) would be to prevent builds for commits by certain users.  Some people working on a repo are documentation only.  We know their pull request wont include code, because they cant edit source code to save their own life.

**Comment by viktorbenei** [comment]
@jayvdb 

> We know their pull request wont include code, because they cant edit source code to save their own life.

How does that work? I mean, is there an option on GitHub to limit this? If there isn't, then it's a bit of a safety issue, as you would not run a test even if their push/PR would include a code change.

**Comment by jayvdb** [comment]
If they did include a code change in a PR, the people with commit access are still responsible for the commit if they merge it.  They can trigger a build of the PR commit easily if required.

**Comment by viktorbenei** [comment]
We found a couple of edge cases where the proposed solution would not be suitable - especially as we try to plan the new format to be able to support `tags` in the future.

__Note:__ _tag handling will be implemented a bit later, will not be part of the first release of the new `trigger_map` format, but we
definitely plan to implement it in the near future._

The new proposed solution would be:

```
trigger_map:
  # current / compatibility mode (if only `pattern` is defined, none of the new properties)
  - pattern: master
    is_pull_request_allowed: true
    workflow: feature

  # new: separate items
  - push_branch: master
    workflow: feature
  - pr_source_branch: master
    workflow: feature
  - pr_target_branch: master
    workflow: feature
  - tag: 1.*
    workflow: feature

  # new: single item for multiple events
  - push_branch: master
    pr_target_branch: master
    tag: 1.*
    workflow: feature

  # -- edge case: deprecated properties - ignore
  - pattern: master # this will be ignored, because push_branch/pr_.._branch/tag is defined
    is_pull_request_allowed: true # this will be ignored, because push_branch/pr_.._branch/tag is defined
    push_branch: master
    pr_target_branch: master
    tag: 1.*
    workflow: feature

  # -- edge case: both pr source & target
  #    Question: should it be?
  #    1) in case of PR it'll only match if the PR is coming from `feature/*` to `master` (AND operation)
  #    2) or: in case of PR it'll match if the target is `master` OR the source is `feature/*` (OR operation)
  - push_branch: master
    pr_target_branch: master
    pr_source_branch: feature/*
    tag: 1.*
    workflow: feature
```

__Question__ for the last edge case: should it be `AND` or rather `OR` between `pr_target_branch` & `pr_source_branch`, if both defined?
`OR` would be more pragmatic (`OR` is used for the other properties too), but `AND` would allow a pattern
for the use case:

> "do this if PR is FROM `feature/*` TO `master`".


## Alternative style idea:

```
# new: alternative style
  - push:
      branch: master
    pr:
      target_branch: master
    tag: 1.*
    workflow: feature
```

But this would be a bit too complicated for single property items, e.g.:

```
  - push:
      branch: master
    workflow: feature
```

vs

```
  - push_branch: master
    workflow: feature
```

We think that

```
  - push_branch: master
    workflow: feature
```

is probably better, as it's more compact for common use cases (and harder to mess up the indentation, or to forget `:` after `push/pr`).

**Comment by brentleyjones** [comment]
I think it should be `AND`, since you can get `OR` behavior by specifying two different triggers. There would be no other way to specify the `AND` behavior, which is a really nice feature to have (I've had a setup where we want to do different things when merging "feature" branches into "epic" branches, for example, which would be slightly different from just merging small fixes into the same "epic" branch).

**Comment by viktorbenei** [comment]
good point @brentleyjones , indeed that's what we thought too, the only issue is that this would mean that there are property pairs with `OR`, as well as with `AND`, which is not consistent, at least it's impossible to guess from the syntax. Of course, the `pr_` prefix could be an indicator, or the "alternative syntax", which would make this consistent, but we're not fond of the "alternative syntax" because of the reason mentioned (usability / ease of use).

**Comment by viktorbenei** [comment]
@birmacher @godrei what do you think?

**Comment by viktorbenei** [comment]
So, after a discussion, we definitely want it to be an `AND`, but we're not happy about the inconsistency of the format (where certain props are treated with `OR`, while the `pr_` ones with `AND`).

Our current proposal is to use the "alternative syntax" for the `pr` items, which can better explain/highlight the fact that the connection between the PR branch patterns is `AND`, instead of `OR`:

```
  - push_branch: master
    pr:
      source_branch: feature/*
      target_branch: master
    tag: 1.*
    workflow: feature
```

This would mean:

1. if it's a code push on `master`
2. OR a `tag` with `1.*` pattern
3. OR a pull request from `feature/*` to `master` (_`AND`_)

_then_ select the `feature` workflow.

The only issue with this format is that the short version, if you only want to define a pattern for the
pull request target, would be:

```
  - pr:
      target_branch: master
    workflow: feature
```
