### ISSUE TITLE
Failed in UITest for Xamarin.iOS App

### ISSUE THREAD

**Issue by amay077** [bitrise-io/bitrise.io#52]
Hi,

I want to run UITest for Xamarin.iOS App.
But I get errors in build process.

Steps to REPRO as follows:

----
I. Fork from https://github.com/bitrise-samples/xamarin-sample-app to my repository

II. Edit [``AppInitializer.cs``](https://github.com/amay077/xamarin-sample-app/blob/master/UITests/AppInitializer.cs#L13) as [Add UITest to your Xamarin app](http://devcenter.bitrise.io/docs/add-unit-test-to-your-xamarin-app)

III. Add "Xamarin iOS Test" to below "Xamarin Builder" in Workflow Editor

"Xamarin iOS Test"'s input variables are all default.

``bitrise.yml`` as follows:

```
---
format_version: 1.2.0
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
trigger_map:
- pattern: "*"
  is_pull_request_allowed: true
  workflow: primary
workflows:
  primary:
    steps:
    - activate-ssh-key@3.1.0:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@3.2.0: {}
    - script@1.1.1:
        title: Do anything with Script step
    - certificate-and-profile-installer@1.6.0: {}
    - xamarin-user-management@1.0.2:
        run_if: ".IsCI"
    - nuget-restore@0.9.2: {}
    - xamarin-components-restore@0.9.0: {}
    - xamarin-builder@1.3.5: {}
    - xamarin-ios-test@1.0.3: {}
    - deploy-to-bitrise-io@1.2.4: {}
app:
  envs:
  - opts:
      is_expand: false
    BITRISE_PROJECT_PATH: XamarinSampleApp.sln
  - opts:
      is_expand: false
    BITRISE_XAMARIN_CONFIGURATION: Debug
  - opts:
      is_expand: false
    BITRISE_XAMARIN_PLATFORM: iPhoneSimulator
```

IV. Start a build.

V. Gets errors in "(8) xamarin-ios-test@1.0.3" step

> WelcomeTextIsDisplayed
SetUp : System.Exception : Instruments failed to start the app.
Stack trace:
  at Xamarin.UITest.iOS.Instruments.WaitForInstruments (Xamarin.UITest.Shared.Processes.RunningProcess instrumentsProcess) <0x3b48618 + 0x005fb> in <filename unknown>:0 
  at Xamarin.UITest.iOS.Instruments.StartInstrumentsInternal (System.String targetApplication, iOSRunType runType, System.String deviceId, System.String runLoopPath, AppDataMode appDataMode, System.Predicate`1 dropLine) <0x3b25028 + 0x0025b> in <filename unknown>:0 
  at Xamarin.UITest.iOS.Instruments.StartInstrumentsHostLoop (System.String targetApplication, iOSRunType runType, System.String deviceId, System.String fifoPath, AppDataMode appDataMode) <0x3b24978 + 0x000ff> in <filename unknown>:0 
  at Xamarin.UITest.iOS.iOSAppLauncher.StartUsingHostStrategy (System.String targetApplication, Xamarin.UITest.iOS.Instruments instruments, iOSRunType runType, System.String deviceIdentifier, Xamarin.UITest.Shared.Http.HttpClient httpClient, System.Uri deviceUri, Xamarin.UITest.Shared.Artifacts.ArtifactFolder artifactFolder, AppDataMode appDataMode) <0x3b24790 + 0x000ab> in <filename unknown>:0 
…

attach the log file - [b857df28db9e17c7.txt](https://github.com/bitrise-io/bitrise.io/files/380102/b857df28db9e17c7.txt)

----

How can I solve this problem?
Or, please show me a sample to running UITest.
