### ISSUE TITLE
step.yml isn't rendered correctly in workflow manager

### ISSUE THREAD

**Issue by jonasmaturana** [bitrise-io/bitrise.io#61]
## Example 1
The "Xamarin Test Cloud for Android" step has a nice yml description [link](https://github.com/bitrise-steplib/steps-xamarin-test-cloud-for-android/blob/1.2.1/step.yml#L86) like this:
```yaml
 - sign_parameters:
    opts:
      title: "Signing parameters"
      summary: "Signing parameters"
      description: |
        Signing parameters to pass Xamarin Test Cloud.

        Required parameters:
        - PATH-TO-KEYSTORE
        - KEYSTORE-PASSWORD
        - KEYALIAS
        - KEYALIAS-PASSWORD

        Example:
        'keystore <PATH-TO-KEYSTORE> <KEYSTORE-PASSWORD> <KEYALIAS> <KEYALIAS-PASSWORD>'
```

Unfortunately bitrise.io renders it like this. Notice how the list is just a flat string separated by dashes and the example it useless.
![image](https://cloud.githubusercontent.com/assets/382420/18161019/600de254-7030-11e6-928a-e1e8a350b420.png)

## Example 2
From the same step is how a very important comment about when the `BITRISE_XAMARIN_TEST_TO_RUN_ID` output is set isn't rendered.

```yaml
  - BITRISE_XAMARIN_TEST_TO_RUN_ID:
    opts:
      title: Test to run ID.
      description: |
        Test to run ID.

        This output is available only if 'test_cloud_is_async' is set to 'yes'.
```

![image](https://cloud.githubusercontent.com/assets/382420/18161396/144658ae-7032-11e6-84da-6df942f0bfd2.png)
